DECLARE @COLLATE NVARCHAR(100) = 'SQL_Latin1_General_CP1_CI_AS'; -- Collation to change to
SELECT
    'ALTER TABLE [' + C.TABLE_SCHEMA + '].[' + C.TABLE_NAME + '] ALTER COLUMN [' + C.COLUMN_NAME + '] '
    + C.DATA_TYPE + '(' + IIF(C.CHARACTER_MAXIMUM_LENGTH = -1, 'MAX', CONVERT(NVARCHAR(255), C.CHARACTER_MAXIMUM_LENGTH)) + ') '+
    'COLLATE ' + @COLLATE + IIF(C.IS_NULLABLE = 'NO', ' NOT NULL', ' NULL') + CHAR(13) + CHAR(10) + 'GO' [ChangeColumnCollationScript]
FROM
    INFORMATION_SCHEMA.COLUMNS C
INNER JOIN INFORMATION_SCHEMA.TABLES T
ON     T.TABLE_CATALOG = C.TABLE_CATALOG
   AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
   AND T.TABLE_NAME = C.TABLE_NAME
   AND T.TABLE_TYPE = 'BASE TABLE'
WHERE
    C.DATA_TYPE LIKE '%char' OR C.DATA_TYPE LIKE '%text'
